name : Publish pytorch-cuda-12.3.2-ubuntu22.04

on:
  push:
    branches:
    - main
    paths: 
    - .github/workflows/publish-pytorch-cuda-12.3.2-ubuntu22.04.yaml
  

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Navigate to Dockerfile Directory
      run: cd dockerfiles/pytorch-cuda-12.3.2-ubuntu22.04/
    
    - name: Build Docker Image
      run:
        docker login --username ayushsaklani --password ${{secrets.GHCR}} ghcr.io
        docker build . --tag ghcr.io/ayushsaklani/pytorch-cuda-12.3.2-ubuntu22.04:latest
        docker push ghcr.io/ayushsaklani/pytorch-cuda-12.3.2-ubuntu22.04:latest
